version: "3.3"

services:
  db:
    image: mariadb:10.3.9
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./mysql/data:/var/lib/mysql
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

